use_frameworks!

platform :ios, '8.0'

target 'testLibs_Example' do
  pod 'testLibs', :path => '../'

  target 'testLibs_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
